Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -38,7 +38,7 @@ jobs:
             sudo bash -x install.sh -skiphc true -ims false </dev/null || exit $?
           else
             sudo bash -x install.sh -skiphc true -ims false -un ${{ steps.decode.outputs.username }} -p ${{ steps.decode.outputs.password }} \
-              -ci onlyoffice/4testing-communityserver -cpi onlyoffice/4testing-controlpanel -di onlyoffice/4testing-documentserver </dev/null || exit $?
+              -ci onlyoffice/4testing-communityserver --communityversion 12.7.1.1953 -cpi onlyoffice/4testing-controlpanel -di onlyoffice/4testing-documentserver </dev/null || exit $?
           fi
           echo -n "Waiting for all containers to start..."
           timeout 300 bash -c 'while docker ps | grep -q "starting"; do sleep 5; done' && echo "OK" || echo "container_status=timeout" >> $GITHUB_ENV
@@ -58,10 +58,7 @@ jobs:
             fi
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
           done
-          if [ $error -ne 0 ]; then
-            echo "Timeout. Some containers failed."
-            exit 1
-          fi
+          [ $error -eq 1 ] && echo "Timeout. Some containers failed." && exit 1
 
       - name: Print logs for crashed containers
         if: failure()
