Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -52,7 +52,10 @@ jobs:
             [[ "$status" = "running" ]] && color="\033[0;32m" || { color="\033[0;31m"; error=1; }
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
           done
-          [ "$error" -eq 1 ] && { echo "Timeout. Some containers failed."; exit 1; }
+          if [ $error -ne 0 ]; then
+            echo "Timeout. Some containers failed."
+            exit 1
+          fi
 
       - name: Print logs for crashed containers
         if: failure()
