Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -49,18 +49,10 @@ jobs:
           containers=$(docker ps --all --format "{{.Names}}" | grep -v '^$' || true)
           for container in $containers; do
             status=$(docker inspect --format="{{.State.Status}}" "$container")
-            if [ "$status" = "running" ]; then
-              color="\033[0;32m"
-            else
-              color="\033[0;31m"
-              error=1
-            fi
+            [[ "$status" = "running" ]] && color="\033[0;32m" || { color="\033[0;31m"; error=1; }
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
           done
-          if [ $error -ne 0 ]; then
-            echo "Timeout. Some containers failed."
-            exit 1
-          fi
+          [ "$error" -eq 1 ] && { echo "Timeout. Some containers failed."; exit 1; }
 
       - name: Print logs for crashed containers
         if: failure()
