Test

diff --git a/.github/workflows/ci-docker-install.yml b/.github/workflows/ci-docker-install.yml
--- a/.github/workflows/ci-docker-install.yml
+++ b/.github/workflows/ci-docker-install.yml
@@ -1,4 +1,4 @@
-name: Install Workspace Docker
+name: Install Workspace Docker copy
 
 on:
   schedule:
@@ -6,11 +6,12 @@ on:
   push:
     branches:
       - 'master'
+      - 'test'
   workflow_dispatch:
 
 jobs:
   Install-Workspace-Docker:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     timeout-minutes: 10
     steps:
       - name: Checkout Repository
@@ -24,46 +25,15 @@ jobs:
 
       - name: Configure Docker credentials
         run: |
-          rm -f ~/.docker/config.json
-          mkdir -p ~/.docker
+          sudo mkdir -p /root/.docker
           echo '{
               "auths": {
-                  "https://index.docker.io/v1/": {
-                      "auth": "${{ secrets.DOCKER_AUTH_KEY }}"
-                  }
+                "https://index.docker.io/v1/": {
+                  "auth": "${{ secrets.DOCKER_AUTH_KEY }}"
+                }
               }
-          }' > ~/.docker/config.json
-          chmod 600 ~/.docker/config.json
-
-      - name: Get latest version for Community Server
-        id: community
-        run: |
-          LATEST=$(curl -s "https://hub.docker.com/v2/repositories/onlyoffice/4testing-communityserver/tags/" \
-            | jq -r '.results[].name' \
-            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$' \
-            | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n \
-            | tail -n1)
-          echo "LATEST_COMMUNITY=$LATEST" >> $GITHUB_ENV
-
-      - name: Get latest version for Control Panel
-        id: controlpanel
-        run: |
-          LATEST=$(curl -s "https://hub.docker.com/v2/repositories/onlyoffice/4testing-controlpanel/tags/" \
-            | jq -r '.results[].name' \
-            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$' \
-            | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n \
-            | tail -n1)
-          echo "LATEST_CONTROLPANEL=$LATEST" >> $GITHUB_ENV
-
-      - name: Get latest version for Document Server
-        id: documentserver
-        run: |
-          LATEST=$(curl -s "https://hub.docker.com/v2/repositories/onlyoffice/4testing-documentserver/tags/" \
-            | jq -r '.results[].name' \
-            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$' \
-            | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n \
-            | tail -n1)
-          echo "LATEST_DOCUMENT=$LATEST" >> $GITHUB_ENV
+          }' | sudo tee /root/.docker/config.json > /dev/null
+          sudo chmod 600 /root/.docker/config.json
 
       - name: Test Workspace Docker scripts
         run: |
@@ -72,46 +42,74 @@ jobs:
             sudo bash -x install.sh -skiphc true -ims false </dev/null || exit $?
           else
             echo "Using 4testing images (non-master branch)..."
-            echo "Community version: $LATEST_COMMUNITY"
-            echo "ControlPanel version: $LATEST_CONTROLPANEL"
-            echo "Document version: $LATEST_DOCUMENT"
-
             sudo bash -x install.sh \
               -skiphc true \
               -ims false \
               --communityimage onlyoffice/4testing-communityserver \
-              --communityversion $LATEST_COMMUNITY \
+              --communityversion 12.7.1.1954 \
               --controlpanelimage onlyoffice/4testing-controlpanel \
-              --controlpanelversion $LATEST_CONTROLPANEL \
+              --controlpanelversion 3.5.4.541 \
               --documentimage onlyoffice/4testing-documentserver \
-              --documentversion $LATEST_DOCUMENT \
               </dev/null || exit $?
           fi
-
-      - name: Waiting for containers
-        run: |
           echo -n "Waiting for all containers to start..."
           timeout 300 bash -c 'while docker ps | grep -q "starting"; do sleep 5; done' && echo "OK" || echo "container_status=timeout" >> $GITHUB_ENV
+          
+
+      # - name: Test Workspace Docker scripts
+      #   run: |
+      #     if [ "${{ github.ref }}" = "refs/heads/master" ]; then
+      #       echo "Using official images (master branch)..."
+      #       sudo bash -x install.sh -skiphc true -ims false </dev/null || exit $?
+      #     else
+      #       echo "Using 4testing images (non-master branch)..."
+      #       sudo bash -x install.sh \
+      #         -skiphc true \
+      #         -ims false \
+      #         --communityimage onlyoffice/4testing-communityserver \
+      #         --communityversion 12.7.1.1953 \
+      #         --controlpanelimage onlyoffice/4testing-controlpanel \
+      #         --controlpanelversion 3.5.4.541 \
+      #         --documentimage onlyoffice/4testing-documentserver \
+      #         --documentversion 8.3.1.19 \
+      #         </dev/null || exit $?
+      #     fi
+      #     echo -n "Waiting for all containers to start..."
+      #     timeout 300 bash -c 'while docker ps | grep -q "starting"; do sleep 5; done' && echo "OK" || echo "container_status=timeout" >> $GITHUB_ENV
 
       - name: Check container status
         run: |
-          docker ps --all --format "{{.Names}}" | while read container; do
-            status=$(docker inspect --format="{{.State.Status}}" $container)
+          error=0
+          while read container; do
+            status=$(docker inspect --format="{{.State.Status}}" "$container")
             color=$([ "$status" == "running" ] && echo "\033[0;32m" || echo "\033[0;31m")
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
             if [ "$status" != "running" ]; then
-              echo "Container $container is not running!" >> $GITHUB_ENV
-              exit 1
+              echo "Container $container is not running!"
+              error=1
             fi
-          done
+          done < <(docker ps --all --format "{{.Names}}")
+          
+          if [ $error -eq 1 ]; then
+            echo "Timeout. Some containers failed."
+            exit 1
+          fi
 
       - name: Print logs for crashed container
+        if: always()
         run: |
+          echo "Collecting logs for containers not running:"
           docker ps --all --format "{{.Names}}" | while read container; do
             if [ "$(docker inspect --format="{{.State.Status}}" $container)" != "running" ]; then
               echo "Logs for container $container:"
-              docker logs --tail 30 $container | sed "s/^/\t/g"
+              docker logs --tail 30 $container | sed "s/^/\t/"
             fi
           done
-          [[ "${{ env.container_status }}" == "timeout" ]] && echo "Timeout. Some containers failed." && exit 1 || echo "All containers are running."
+
+      - name: Fail if containers not running
+        if: ${{ env.container_status == 'timeout' }}
+        run: |
+          echo "Timeout. Some containers failed."
+          exit 1
+
 
