Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -38,24 +38,24 @@ jobs:
             sudo bash -x install.sh -skiphc true -ims false </dev/null || exit $?
           else
             sudo bash -x install.sh -skiphc true -ims false -un ${{ steps.decode.outputs.username }} -p ${{ steps.decode.outputs.password }} \
-              -ci onlyoffice/4testing-communityserver --communityversion 12.7.1.1953 -cpi onlyoffice/4testing-controlpanel -di onlyoffice/4testing-documentserver </dev/null || exit $?
+              -ci onlyoffice/4testing-communityserver --communityversion 12.7.1.1953-cpi onlyoffice/4testing-controlpanel -di onlyoffice/4testing-documentserver </dev/null || exit $?
           fi
           echo -n "Waiting for all containers to start..."
           timeout 300 bash -c 'while docker ps | grep -q "starting"; do sleep 5; done' && echo "OK" || echo "container_status=timeout" >> $GITHUB_ENV
 
       - name: Check container status
         run: |
-          docker ps --all --format "{{.Names}}" | while read container; do
-            status=$(docker inspect --format="{{.State.Status}}" $container)
-            color=$([ "$status" == "running" ] && echo "\033[0;32m" || echo "\033[0;31m")
+          error=0
+          containers=$(docker ps --all --format "{{.Names}}" | grep -v '^$' || true)
+          for container in $containers; do
+            status=$(docker inspect --format="{{.State.Status}}" "$container")
+            [[ "$status" = "running" ]] && color="\033[0;32m" || { color="\033[0;31m"; error=1; }
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
-            if [ "$status" != "running" ]; then
-              echo "Container $container is not running!" >> $GITHUB_ENV
-              exit 1
-            fi
           done
+          [ "$error" -eq 0 ] || { echo "Timeout. Some containers failed."; exit 1; }
 
       - name: Print logs for crashed containers
+        if: failure()
         run: |
           docker ps --all --format "{{.Names}}" | while read container; do
             if [ "$(docker inspect --format="{{.State.Status}}" $container)" != "running" ]; then
