Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -52,10 +52,7 @@ jobs:
             [[ "$status" = "running" ]] && color="\033[0;32m" || { color="\033[0;31m"; error=1; }
             printf "%-50s ${color}%s\033[0m\n" "$container" "$status"
           done
-          if [ $error -ne 0 ]; then
-            echo "Timeout. Some containers failed."
-            exit 1
-          fi
+          [ "${error:-0}" -ne 0 ] && echo "Timeout. Some containers failed." && exit 1
 
       - name: Print logs for crashed containers
         if: failure()
