Update ci-docker-install copy.yml

diff --git a/.github/workflows/ci-docker-install copy.yml b/.github/workflows/ci-docker-install copy.yml
--- a/.github/workflows/ci-docker-install copy.yml
+++ b/.github/workflows/ci-docker-install copy.yml
@@ -23,19 +23,18 @@ jobs:
         run: |
           sudo docker image prune --all --force
 
-
       - name: Configure Docker credentials
         run: |
-                rm -f ~/.docker/config.json
-                mkdir -p ~/.docker
-                echo '{
-                    "auths": {
-                    "https://index.docker.io/v1/": {
-                        "auth": "${{ secrets.DOCKER_AUTH_KEY }}"
-                    }
-                    }
-                }' > ~/.docker/config.json
-                chmod 600 ~/.docker/config.json
+          rm -f ~/.docker/config.json
+          mkdir -p ~/.docker
+          echo '{
+              "auths": {
+                "https://index.docker.io/v1/": {
+                  "auth": "${{ secrets.DOCKER_AUTH_KEY }}"
+                }
+              }
+          }' > ~/.docker/config.json
+          chmod 600 ~/.docker/config.json
 
       - name: Copy Docker credentials for root
         run: |
@@ -77,12 +76,20 @@ jobs:
           done
 
       - name: Print logs for crashed container
+        if: always()
         run: |
+          echo "Collecting logs for containers not running:"
           docker ps --all --format "{{.Names}}" | while read container; do
             if [ "$(docker inspect --format="{{.State.Status}}" $container)" != "running" ]; then
               echo "Logs for container $container:"
-              docker logs --tail 30 $container | sed "s/^/\t/g"
+              docker logs --tail 30 $container | sed "s/^/\t/"
             fi
           done
-          [[ "${{ env.container_status }}" == "timeout" ]] && echo "Timeout. Some containers failed." && exit 1 || echo "All containers are running."
+
+      - name: Fail if containers not running
+        if: ${{ env.container_status == 'timeout' }}
+        run: |
+          echo "Timeout. Some containers failed."
+          exit 1
+
 
